name: alkitab_models
description: Shared domain models for Alkitab apps.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner:
  json_serializable: ^6.9.0
  flutter_lints: ^5.0.0
