// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDStazq-kPAK_Rp5u-Q9gBGJPFPjKvwkPI',
    appId: '1:546585126869:android:7f018ef78d982314807f5c',
    messagingSenderId: '546585126869',
    projectId: 'qudwa-2d66a',
    storageBucket: 'qudwa-2d66a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzvHII15doZL_qkSXH-CzuXCku2kkPfCA',
    appId: '1:546585126869:ios:dbe8a1df9f3d9062807f5c',
    messagingSenderId: '546585126869',
    projectId: 'qudwa-2d66a',
    storageBucket: 'qudwa-2d66a.firebasestorage.app',
    androidClientId: '546585126869-21ujd47j1bang1mbcir50tlamie8rdhk.apps.googleusercontent.com',
    iosClientId: '546585126869-876q614s3adao6vl5d66bch4hnu3ddi5.apps.googleusercontent.com',
    iosBundleId: 'com.atifiy.qudwa',
  );

}